// Merges app bindings into the global CloudflareEnv interface used by
// @opennextjs/cloudflare's getCloudflareContext(). Runtime types
// (KVNamespace etc.) come from worker-configuration.d.ts generated by
// `wrangler types`.
interface CloudflareEnv {
  NOTEBOOKS_KV: KVNamespace;
}
