import CreateNotebookButton from "@/components/create-notebook-button";

export const dynamic = "force-dynamic";

export default function HomePage() {
  return (
    <div className="mx-auto w-full max-w-2xl flex-1 px-6 py-16 flex flex-col items-center justify-center">
      <header className="mb-10 text-center">
        <div className="mb-1 flex items-center justify-center gap-3">
          <span className="flex h-10 w-10 items-center justify-center rounded-none border border-[var(--lf-accent)]/60 bg-[var(--lf-accent)]/10 font-mono text-sm font-bold text-[var(--lf-accent)] shadow-[0_0_18px_rgba(0,0,0,0.25)]">
            LF
          </span>
          <h1 className="font-mono text-2xl font-bold uppercase tracking-[0.18em]" style={{ color: "var(--lf-fg)" }}>
            LessonForge
          </h1>
        </div>
        <p className="ml-13 font-mono text-[5px] uppercase tracking-[0.2em] text-zinc-500">BossG Innovations 2026</p>
        <p className="font-mono text-xs tracking-wide text-zinc-500">
          Source-driven ILAW lesson plans — generated by AI, perfected by human expertise.
        </p>
      </header>

      <section className="lf-panel lf-frame relative w-full p-8">
        <h2 className="mb-3 font-mono text-[11px] font-semibold uppercase tracking-[0.2em] text-[var(--lf-accent)]/60">
          &gt; Welcome
        </h2>
        <p className="max-w-xl text-xs leading-relaxed text-zinc-300">
          LessonForge empowers Cabiao Senior High School faculty to generate fully compliant,
          classroom-ready lesson plans aligned with the ILAW Framework (DepEd Order No. 016, s. 2026).
          Powered by AI and grounded strictly in your selected Senior High School learning strands,
          DepEd modules, and local reference materials, LessonForge eliminates the unverified,
          conflicting content found across general web searches. Every section—from Intentions to
          Ways Forward—is produced as an editable draft, ensuring that Cabiao SHS teachers retain
          full pedagogical control to review, refine, and approve every plan before stepping into
          the classroom.
        </p>
        <ul className="mt-4 space-y-1.5 font-mono text-[11px] text-zinc-500">
          <li className="flex items-center gap-2">
            <span className="text-[var(--lf-accent)]/60">→</span> Follows the official ILAW lesson plan sections
          </li>
          <li className="flex items-center gap-2">
            <span className="text-[var(--lf-accent)]/60">→</span> Each session is private and disappears after you download your plan
          </li>
          <li className="flex items-center gap-2">
            <span className="text-[var(--lf-accent)]/60">→</span> No account required
          </li>
          <li className="flex items-center gap-2">
            <span className="text-[var(--lf-accent)]/60">→</span> Multiple free AI providers supported
          </li>
        </ul>
        <div className="mt-6">
          <CreateNotebookButton />
        </div>
      </section>
    </div>
  );
}
